print("╔═════════════════════════════════════════╗")
print("║\n\nGiriş Yap\n                          ║")
print("║\tNickname\t:\n\tPassword\t:\n\tLevel:999║")
print("╚═════════════════════════════════════════╝")
input()
